name: gym_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.17.0


fl_dependencies:
  flutter:
    sdk: flutter
    fl_chart: ^0.68.0

Google_dependencies:
   flutter:
    sdk: flutter
    google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
